name: Run Notion Script at 3 PM Vietnam Time

on:
  schedule:
    - cron: "*/2 * * * *" 
    #- cron: "9 9 * * *" # Chạy lúc 15h Việt Nam (8h UTC)
  workflow_dispatch:       # Cho phép chạy thủ công từ GitHub Actions

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests

      - name: Run Notion Script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python notion_script.py
